### ISSUE TITLE
Unable to checkout TritonRoute as of 7/8/2020

### ISSUE THREAD

**Issue by terrifictardigrade** [The-OpenROAD-Project/OpenROAD-flow#108]
When running "git clone --recursive https://github.com/The-OpenROAD-Project/OpenROAD-flow.git" I am unable to checkout TritonRoute. I was working on an automated local install script for the tools, and noticed the issue started yesterday afternoon. Cloning and building was successful just a few hours before that, so I think commit a8431c7f5bfb43bbbc614b79806f04047d138214 may be the problem, but I don't know enough about git to say for sure. Output below:

```
Cloning into 'tools/TritonRoute'...
remote: Enumerating objects: 80, done.
remote: Counting objects: 100% (80/80), done.
remote: Compressing objects: 100% (74/74), done.
remote: Total 747 (delta 8), reused 37 (delta 3), pack-reused 667
Receiving objects: 100% (747/747), 3.12 MiB | 0 bytes/s, done.
Resolving deltas: 100% (333/333), done.
fatal: reference is not a tree: dd6972fa70eaca54eebb744627beea0089e5474d
Cloning into 'tools/yosys'...
remote: Enumerating objects: 52455, done.
remote: Total 52455 (delta 0), reused 0 (delta 0), pack-reused 52455
Receiving objects: 100% (52455/52455), 58.21 MiB | 25.42 MiB/s, done.
Resolving deltas: 100% (38419/38419), done.
Submodule path 'tools/yosys': checked out 'ff4ca9ddc3fe3a0ef93feb295bf135ebff03b3df'
Unable to checkout 'dd6972fa70eaca54eebb744627beea0089e5474d' in submodule path 'tools/TritonRoute'
```

**Expected behavior**
Checkout working properly

**Environment (please complete the following information):**
Please only report issues for supported OSs.
 - OS: CentOS 7
 - OpenROAD-flow commit a8431c7f5bfb43bbbc614b79806f04047d138214

**Additional context**
I had a colleague try cloning last night as well and he had the same results, also CentOS 7 and running the same clone command.

**Comment by rovinski** [comment]
This is more likely because of some updates to the TritonRoute repo. I haven't seen anything on my end, but I'll check it out.
