### ISSUE TITLE
Missing file during `make finish`

### ISSUE THREAD

**Issue by stdavids** [The-OpenROAD-Project/OpenROAD-flow#17]
When running 'make finish' on the default design I get the following error message:

```
/home/vagrant/OpenROAD-flow/OpenROAD/build/src/magic: line 61: /home/vagrant/OpenROAD-flow/OpenROAD/lib/magic/tcl/magicdnull: No such file or directory
```

**Comment by rovinski** [comment]
I noticed the magic files missing this morning and committed edf7173. Try pulling and see if the issue is fixed.

**Comment by rovinski** [comment]
This was just fixed in
