### ISSUE TITLE
Missing PORT9.dat file

### ISSUE THREAD

**Issue by tunghoang290780** [The-OpenROAD-Project/OpenROAD-flow#21]
This PORT9.dat file must be copied into OpenROAD-flow/OpenROAD/etc similar to other POWV9.dat, POST9.dat. The PORT9.dat belongs to the yosys package

**Comment by tajayi** [comment]
I am aware that the  PORT9.dat file is not included in the OpenROAD build. I believe it only requires FluteLUT files: POWV9.dat and POST9.dat.

Can you please elaborate on any specific issue you are experiencing? Did you get an error while performing some operation?

**Comment by tunghoang290780** [comment]
So far, I do not see the problem with the missing file PORT9.dat. If that file is no longer use, it is possible to clean up Makefile or script that refer to the PORT9 file

**Comment by tajayi** [comment]
I assume you are referring to https://github.com/The-OpenROAD-Project/OpenROAD-flow/blob/master/flow/Makefile#L126?

It was used once upon a time ago but didn't get cleaned up. I have deleted references to that file in a local commit. It'll take some time before being pushed.

Thanks

**Comment by tunghoang290780** [comment]
Hi @tajayi 

That is correct! Thanks

**Comment by rovinski** [comment]
*.dat files are no longer required as of 048a503. This issue should be resolved now.
