### ISSUE TITLE
Update to magic needed

### ISSUE THREAD

**Issue by RTimothyEdwards** [The-OpenROAD-Project/OpenROAD-flow#33]
This is possibly off-topic, because I think that magic is not currently part of the OpenROAD flow integration.  However, I could not find an issue tracker on the magic fork, so I'm posting it here.

A couple of days ago I found a problem in one of the original algorithms in magic for ext2spice extraction, which was particularly badly suited to standard cell layouts and caused an exponentially rising compute time with the size of a layout, resulting in hours-long runs for small microcontoller-sized designs, and becoming unusable for sizes beyond that.  Fortunately, a simple fix to the algorithm knocked it down from hours to seconds.  Behavior should now be approximately linear with design size (i.e., gate count).  I also found several behaviors in the initial "extract" command that also could be modified to knock down the execute time, not as significantly as the ext2spice algorithm, but still significant.

I have a branch "bplane" in the magic repo that knocks the extraction time down by another 3x or so, although that modification is far-reaching and I have not completely vetted all the commands that it effects, so I do not recommend using it at this point, but I will let you know when I have finished vetting it and merge the code back into the master branch.

Anyway, the bottom line is please update the fork of magic on your site to the latest git repo, as it is much better suited to large standard cell layouts for extraction and netlisting.  GDS generation is not impacted by this change, although the bplane branch may show some improvement (again, not vetted).

Thanks,
Tim

**Comment by rovinski** [comment]
Hi @RTimothyEdwards,

Thanks for the heads-up. Our flow no longer depends on Magic on the stable or development branches, so we should be unaffected.
