### ISSUE TITLE
Problem to build with "Option 1"

### ISSUE THREAD

**Issue by wlneto** [The-OpenROAD-Project/OpenROAD-flow#58]
Hi, 

I have been trying to set up the OpenROAD flow through the 1st option (installing the builds). I'm using CentOS, and after following the steps (recursive cloning, untar the release, and setup_env), I'm not able to go beyond Yosys step. 

When running "make" in the flow folder, I get a /usr/bin/time permission error during the "openroad -no_init -exit ./scripts/floorplan.tcl" step. 
However, I can run "/usr/bin/time", and I think that the setup_env is missing something, as I cannot run "openroad -h" for instance. Looking at the setup env script, I think I should have a "build" folder inside the "OpenROAD-flow/tools/," which I don't.  

Am I missing something? 
Thanks in advance for your help.

**Comment by rovinski** [comment]
Option 1 is not really viable right now until OpenROAD gets a more automated release system. It is on our road map, but we have sponsor-mandated goals that we have to meet by July. We don't really have resources to spare until then. Please use option 2 or 3 for now.
